package com.sdg.energytracker.models;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * EnergyUsageRecord.java
 * 
 * This class records and stores the energy consumption data generated by
 * appliances. It demonstrates several OOP principles:
 * 
 * ENCAPSULATION: All attributes are private with controlled access via
 * getters and setters. The record data is protected from direct modification.
 * 
 * POLYMORPHISM: The constructor accepts an Appliance reference, which can
 * point to any subclass object (LightAppliance, CoolingAppliance, etc.).
 * When calculateEnergyConsumption() is called on this reference, the
 * correct overridden version executes automatically — this is runtime
 * polymorphism (dynamic dispatch) in action.
 * 
 * This class supports SDG 7 by providing a structured way to log and
 * analyse household energy usage patterns, enabling data-driven decisions
 * for reducing energy waste.
 * 
 * @author Group Work
 * @version 1.0
 */
public class EnergyUsageRecord {

    // ==================== ENCAPSULATION ====================
    // All fields are private — external access is only through getters/setters.

    /** Unique identifier for this energy usage record. */
    private int recordId;

    /** The appliance associated with this energy record. */
    private Appliance appliance;

    /** The calculated energy consumption in kilowatt-hours (kWh). */
    private double energyConsumedInKWh;

    /** The date and time when this record was created. */
    private LocalDateTime recordDateTime;

    /** Static counter to auto-generate unique record IDs. */
    private static int nextId = 1;

    // ==================== CONSTRUCTORS ====================

    /**
     * Default (no-argument) constructor.
     * Initialises the record with default values and auto-generates an ID.
     */
    public EnergyUsageRecord() {
        this.recordId = nextId++;
        this.appliance = null;
        this.energyConsumedInKWh = 0.0;
        this.recordDateTime = LocalDateTime.now();
    }

    /**
     * Parameterised constructor.
     * Accepts an Appliance object (which could be any subclass thanks to
     * POLYMORPHISM) and automatically calculates the energy consumption.
     * 
     * Because the parameter type is 'Appliance' (the superclass), we can pass
     * in a LightAppliance, CoolingAppliance, or any future subclass.
     * The correct overridden calculateEnergyConsumption() method will be
     * called at runtime — this is POLYMORPHISM in action.
     *
     * @param appliance the appliance to record energy usage for
     * @throws IllegalArgumentException if appliance is null
     */
    public EnergyUsageRecord(Appliance appliance) {
        // ENCAPSULATION: Validate input to protect data integrity
        if (appliance == null) {
            throw new IllegalArgumentException("Appliance cannot be null.");
        }
        this.recordId = nextId++;
        this.appliance = appliance;

        // DYNAMIC POLYMORPHISM (Runtime Polymorphism): The parameter 'appliance' is declared
        // as the superclass type (Appliance), but the actual object passed in
        // could be a LightAppliance, CoolingAppliance, or any future subclass.
        // When calculateEnergyConsumption() is called here, the JVM uses
        // DYNAMIC DISPATCH to invoke the correct overridden version at runtime.
        this.energyConsumedInKWh = appliance.calculateEnergyConsumption();
        this.recordDateTime = LocalDateTime.now();
    }

    // ==================== GETTERS & SETTERS ====================

    /**
     * Gets the unique record ID.
     *
     * @return the record ID
     */
    public int getRecordId() {
        return recordId;
    }

    /**
     * Gets the appliance associated with this record.
     *
     * @return the Appliance object
     */
    public Appliance getAppliance() {
        return appliance;
    }

    /**
     * Sets the appliance for this record and recalculates energy consumption.
     * Demonstrates POLYMORPHISM — the appropriate calculateEnergyConsumption()
     * is invoked based on the actual type of the appliance passed in.
     *
     * @param appliance the appliance to set
     * @throws IllegalArgumentException if appliance is null
     */
    public void setAppliance(Appliance appliance) {
        if (appliance == null) {
            throw new IllegalArgumentException("Appliance cannot be null.");
        }
        this.appliance = appliance;
        // Recalculate energy when the appliance changes (POLYMORPHISM)
        this.energyConsumedInKWh = appliance.calculateEnergyConsumption();
    }

    /**
     * Gets the energy consumed in kilowatt-hours.
     *
     * @return the energy consumption in kWh
     */
    public double getEnergyConsumedInKWh() {
        return energyConsumedInKWh;
    }

    /**
     * Sets the energy consumed in kilowatt-hours.
     * ENCAPSULATION: Validates that energy consumption is not negative,
     * ensuring data integrity through controlled access.
     *
     * @param energyConsumedInKWh the energy consumption to set (must be >= 0)
     * @throws IllegalArgumentException if energyConsumedInKWh is negative
     */
    public void setEnergyConsumedInKWh(double energyConsumedInKWh) {
        if (energyConsumedInKWh < 0) {
            throw new IllegalArgumentException(
                    "Energy consumed cannot be negative. Received: " + energyConsumedInKWh);
        }
        this.energyConsumedInKWh = energyConsumedInKWh;
    }

    /**
     * Gets the date and time when this record was created.
     *
     * @return the record date and time
     */
    public LocalDateTime getRecordDateTime() {
        return recordDateTime;
    }

    /**
     * Sets the record date and time.
     *
     * @param recordDateTime the date and time to set
     * @throws IllegalArgumentException if recordDateTime is null
     */
    public void setRecordDateTime(LocalDateTime recordDateTime) {
        if (recordDateTime == null) {
            throw new IllegalArgumentException("Record date/time cannot be null.");
        }
        this.recordDateTime = recordDateTime;
    }

    // ==================== UTILITY METHODS ====================

    /**
     * Generates a formatted summary of this energy usage record.
     * This method provides a detailed, human-readable report including
     * appliance details, energy consumption, and a sustainability tip.
     *
     * @return a formatted string report of the energy record
     */
    public String generateReport() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        StringBuilder report = new StringBuilder();

        report.append("========================================\n");
        report.append("       ENERGY USAGE RECORD REPORT       \n");
        report.append("========================================\n");
        report.append(String.format("Record ID       : %d%n", recordId));
        report.append(String.format("Date/Time       : %s%n", recordDateTime.format(formatter)));

        if (appliance != null) {
            report.append(String.format("Appliance Name  : %s%n", appliance.getApplianceName()));
            report.append(String.format("Power Rating    : %.2f W%n", appliance.getPowerRatingInWatts()));
            report.append(String.format("Usage Duration  : %.2f h%n", appliance.getUsageDurationInHours()));
            report.append(String.format("Energy Consumed : %.4f kWh%n", energyConsumedInKWh));

            // Display appliance-specific information using instanceof
            if (appliance instanceof LightAppliance) {
                LightAppliance light = (LightAppliance) appliance;
                report.append(String.format("Type            : Light (%s)%n",
                        light.getIsLED() ? "LED - Energy Efficient" : "Non-LED"));
            } else if (appliance instanceof CoolingAppliance) {
                CoolingAppliance cooling = (CoolingAppliance) appliance;
                report.append(String.format("Type            : Cooling (Set to %d°C)%n",
                        cooling.getTemperatureSetting()));
            }
        } else {
            report.append("Appliance       : Not set\n");
        }

        report.append("----------------------------------------\n");
        report.append("SDG 7 Tip: Save energy by using LED\n");
        report.append("lights and setting AC to 24°C or above!\n");
        report.append("========================================\n");

        return report.toString();
    }

    /**
     * Returns a concise string representation of the EnergyUsageRecord.
     *
     * @return a formatted string containing the record summary
     */
    @Override
    public String toString() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String appName = (appliance != null) ? appliance.getApplianceName() : "N/A";
        return String.format("EnergyUsageRecord [ID: %d, Appliance: %s, Energy: %.4f kWh, Time: %s]",
                recordId, appName, energyConsumedInKWh, recordDateTime.format(formatter));
    }
}
